### ISSUE TITLE
Issue regarding whitespace minification

### ISSUE THREAD

**Issue by connorjclark** [terser/html-minifier-terser#122]
Cross-posting from an issue on emscripten, which uses this tool

https://github.com/emscripten-core/emscripten/issues/16656

![image](https://user-images.githubusercontent.com/4071474/161445083-6b830c81-9a59-4027-821c-f877e683e1fa.png)

**Comment by DanielRuf** [comment]
Hi @connorjclark,

thanks for reporting this.

Please check the settings at https://terser.org/html-minifier-terser/ and play a bit with these.

Can you please share a reproducible testcase with html code that we can copy and paste? The image is not that helpful for us. Thank you very much.

**Comment by connorjclark** [comment]
```html
<p>
        To report issues, contact Connor (discord connorclark#9300) or file an issue on the <a target="_blank"
          href="https://github.com/ArmageddonGames/ZeldaClassic">GitHub</a> issue tracker.
      </p>
```

```
npx html-minifier-terser tmp.html --collapse-inline-tag-whitespace
```

result
```html
<p>To report issues, contact Connor (discord connorclark#9300) or file an issue on the <a target="_blank" href="https://github.com/ArmageddonGames/ZeldaClassic">GitHub</a> issue tracker.</p>
```

**Comment by DanielRuf** [comment]
The maintainers of emscripten should probably remove the inline option. There are good reasons why "Collapse inline tag whitespace" is in red. Because it can break stuff.

In html-minifier all options / flags are disabled by default as you can see in the readme. Please tell the emscripten maintainers that the `collapseInlineTagWhitespace` should be removed.

Nothing to fix on our end since it works like expected.

See also:
https://github.com/kangax/html-minifier/issues/1082
https://github.com/kangax/html-minifier/issues/691
https://github.com/kangax/html-minifier/issues/706#issuecomment-242338368
