### ISSUE TITLE
Can't seem to get to work with Jquery in a file. 

### ISSUE THREAD

**Issue by bad-jesus** [terser/html-minifier-terser#130]
I keep getting parsing errors when trying to use this on a file with Jquery. 

Parse Error: < 0 ? this[ num + this.length ] : this[ num ];

Anyone else running into this?

**Comment by DanielRuf** [comment]
Please provide a reproducible test case as html file or similar and provide the exact steps to reproduce.

You can test on https://terser.org/html-minifier-terser/

**Comment by DanielRuf** [comment]
Hi,

thanks for reporting this issue.

Can you please provide a reproducible test case as html file or similar and provide the exact steps to reproduce?
You can also test on https://terser.org/html-minifier-terser/

**Comment by bad-jesus** [comment]
Sorry, I should have included more info.

If you copy and paste jquery and try and min it, you get the error.

Screenshot :

***@***.***

**Comment by DanielRuf** [comment]
For me it works there:

<img width="694" alt="Bildschirmfoto 2022-07-26 um 23 36 06" src="https://user-images.githubusercontent.com/827205/181116590-dcedae9a-06f8-484e-afc1-9d9c1837abcb.png">

Please make sure to use html files with `<script>` tags in them, so that html-minifier can compress these blocks with terser.
All js compression logic comes from terser directly.

**Comment by bad-jesus** [comment]
Hi Daniel,
I tried to set up something to share, but it is rather involved as it is being used as part of a project.

because the file was not being included in an HTML, having the <script> tag wasn’t possible without then stripping it out after. That very well could be the issue.
What we ended up doing, is just bypassing the terser entirely and gzipping the already minified jquery file right on to the chip.

Thank you for the quick responses though.

Jamie
