### ISSUE TITLE
Compress script data block

### ISSUE THREAD

**Issue by willfarrell** [terser/html-minifier-terser#34]
For google datasets to work it requires Schema.org JSON-LD inline script tag on a page. Compression of this by default or behind a flag would be awesome.

Example
```
<script type="application/ld+json">
{
        "@context": {
            "@vocab":"https://schema.org/"
        },
        "@type": "Dataset"
}
</script>
```

**Comment by DanielRuf** [comment]
Hi @willfarrell,

even if we would add the `application/ld+json` to the allowed script mimetypes, it would not make a big difference.

![image](https://user-images.githubusercontent.com/827205/75777680-ab41ac80-5d56-11ea-9962-6f7707e704c8.png)

Because in general this is not valid JavaScript but JSON and this library compresses HTML + JavaScript and CSS. But JSON is not JavaScript.

**Comment by mauriciabad** [comment]
Terser has an option to parse just an expression:
```
--parse expression
```

This may minify the JSON.

**Comment by DanielRuf** [comment]
Hi @mauriciabad,

I'm not sure how we can add this in html-minifier-terser.
This would be a new feature as html-minifier-terser compresses only js, css and html but no other formats afaik.

Prs which add this are very welcome.

**Comment by DanielRuf** [comment]
> This may minify the JSON.

Does it minify it? I'm not sure if this compresses every available form of JSON. Would be good if someone can test and verify this so we can discuss possible solutions.

**Comment by liuycy** [comment]
`{ processScripts: ['application/ld+json'] }`

Pass an option like this works for me.
