### ISSUE TITLE
update terser to latest version (5)

### ISSUE THREAD

**Issue by alexander-akait** [terser/html-minifier-terser#46]
Will be great to do it ASAP to avoid multiple dependencies, thanks for work on the package, plus update old deps too :smile: If you need I can help at the end of week

**Comment by DanielRuf** [comment]
> to avoid multiple dependencies

Not sure what you mean with this.

> plus update old deps too

Which dependencies exactly do you mean?

According to https://github.com/terser/terser/blob/master/CHANGELOG.md#v500-beta0 the minimum required Node version is `10`(but the code in package.json still says `6`). And there are a few more breaking changes. So this will not happen asap.

This needs further clarification because webpack 4 supports Node 6+.
https://github.com/DanielRuf/html-minifier-terser/blob/master/package.json#L52

cc @fabiosantoscode

**Comment by evilebottnawi** [comment]
@DanielRuf You can do major release, as we will do for `terser-webpack-plugin`. developers who want to support node@6, can you old version, this is a normal technical process, drop old node and update terser is not hard

**Comment by DanielRuf** [comment]
I will wait for the feedback of @fabiosantoscode. I do nopt plan to maintain two major versions at the same time so the upgrade will not happen soon.

Please keep in mind that dependents like the html-webpack-plugin would use the old version which I would not maintain then.

https://www.npmjs.com/package/html-minifier-terser

> developers who want to support node@6, can you old version, this is a normal technical process, drop old node and update terser is not hard

I can not simply drop that because webpack 4 will still support Node 6 for a very long time. So this is not an option. Otherwise there will be issues like https://github.com/DanielRuf/html-minifier-terser/issues/22 and more which produces extra work and makes the upgrade and major version bump senseless for the near future.

**Comment by DanielRuf** [comment]
I'll wait until webpack 5 is released and webpack 4 deprecated.

**Comment by evilebottnawi** [comment]
> I will wait for the feedback of @fabiosantoscode. I do nopt plan to maintain two major versions at the same time so the upgrade will not happen soon.

Okay, I will do fork and will use it in webpack packages

**Comment by evilebottnawi** [comment]
> I'll wait until webpack 5 is released and webpack 4 deprecated.

No need, it only creates problems, most of developers do not use 6 node, almost loaders and plugins supports only node@10, you can look at `package.json`

**Comment by DanielRuf** [comment]
Not sure why this is needed and I don't think this is helpful. This will likely break all webpack 4 setups.

Still, what do you want to resolve by upgrading to terser 5 in this package here?

**Comment by DanielRuf** [comment]
> No need, it only creates problems, most of developers do not use node 6, almost loaders and plugins supports only node@10, you can look at `package.json`

Which package.json? I look at the package.json of webpack. And The html-webpack-plugin maintained by @jantimon.

**Comment by DanielRuf** [comment]
> No need, it only creates problems

I see no problem by supporting minimum Node version. Please clarify which problems you mean.
Currently the whole discussion does not provide good reasons to upgrade right now or rush this until webpack 5 is finally released.

**Comment by evilebottnawi** [comment]
I update original answer https://github.com/DanielRuf/html-minifier-terser/issues/46#issuecomment-668517987

**Comment by DanielRuf** [comment]
> And you should not maintain two packages

This is not what I mean, if we upgrade (which results in html-minifier-terser v6) we may still have to support v5 by maintaining a second branch (which is done by many big projects).

**Comment by evilebottnawi** [comment]
Big projects can migrate on v5, supporting EOL node version is unsafe

**Comment by evilebottnawi** [comment]
> Still, what do you want to resolve by upgrading to terser 5 in this package here?

This package uses in html-loader, so we need to upgrade terser to avoid future problems with minimizing

**Comment by evilebottnawi** [comment]
> Currently the whole discussion does not provide good reasons to upgrade right now or rush this until webpack 5 is finally released.

Are you seriously? Node 6 does not receive security updates, it potentially contains vulnerabilities, no project will use this in production

**Comment by DanielRuf** [comment]
Toi clarify my opinion:

> What you are trying to do only creates difficulties and problems:
> 
>  * Almost of developers migrate on node@10
Which problems / difficulties does this cause? I see none.


>  * Using old version of terser do not have bug fixes, so you can break code
I am still waiting for the feedback from @fabiosantoscode.


>  * Keeping old verison of deps and support node@6 is potential unsafe, because many old deps other have security problems

You did not show any relevant advisories or npm audit reports ;-)

> Using old version of terser do not have bug fixes, so you can break code

This can be easily backported.

> Big projects ~can~ **should** migrate on new node version, supporting EOL version is unsafe

Well, tell that webpack and others ;-)

> Are you seriously? Node 6 does not receive security updates, it potentially contains vulnerabilities, no project will use this in production

Well, tell that webpack and others ;-)

> This package uses in html-loader, so we need to upgrade terser to avoid future problems with minimizing

Citation needed, where are currently problems with minimizing? I see no relevant bugfixes at https://github.com/terser/terser/blob/master/CHANGELOG.md#v500

Please calm down and do not rush. At least producing pressure on me does not help at all. And I want to avoid issues like in the past due to breaking installs reported to @jantimon and others.

**Comment by evilebottnawi** [comment]
> You did not show any relevant advisories or npm audit reports ;-)

Please read node docs about minimum usage, they recommend never to use EOL node version (it is **insecurity**), safety is always matter

> This can be easily backported.

terser does not bug port fixes in old version

> Well, tell that webpack and others ;-)

Already, so we drop node@6 and node@8 support from all loaders and plugins, I tell you how core developers of webpack

> Citation needed, where are currently problems with minimizing? I see no relevant bugfixes at https://github.com/terser/terser/blob/master/CHANGELOG.md#v500

> in operator now taken into account during property mangle.
> Fixed infinite loop in face of a reference loop in some situations.

What is it? It is fixes, so if somebody will use it in code, it will be problem.

> Please calm down and do not rush. At least producing pressure on me does not help at all. And I want to avoid issues like in the past due to breaking installs reported to @jantimon and others.

Okay, as I said before time to fork this projects and maybe time to fork html-webpack-plugin, lately this creates only problems, my attempt to fix the process leads to nowhere, requests to fix and pay attention to very important things are ignored. I'm not putting pressure on you, I'm just trying to explain that such an approach currently creates problems, and will create even more in the future, I'm trying to prevent them at the start. I don't see any problem with dependency updates and don't use a old node. Supporting EOL node version is the worst idea. webpack@4 support node@6 due historical reasons. The new webpack version might even skip version 10 to avoid the same problem in future. All this I say as a developer who spends most of the time maintaining webpack and webpack ecosystem.

**Comment by evilebottnawi** [comment]
And the most important thing - backporting is the last resort when there is no way to update at all, it is a very bad idea to use this as a standard approach

**Comment by DanielRuf** [comment]
Good luck with this. terser 5 is only 3 days old. I see no good reasons to rush this.

**Comment by evilebottnawi** [comment]
And please tell me what this package has to do with the webpack? What if I use it in completely different places and ask to do update, because my code is broken due terser bugs? Still don't think this is a problem? i can create repository with issue or will that be ignored too?

**Comment by fabiosantoscode** [comment]
Hey there! I missed my mentions :)

Terser 5 does drop older node support. Thanks for pointing out that package.json still says node 6 :) I'll change it when I have the time.

I don't think there's any rush in moving to Terser 5 either! It's just been released.

The real issue with updating is probably not going to be the node version (as most of your users are probably on node >=10), but the fact that the minify() function is now async (I'm very sorry but I have to update to the new source-map). This will warrant a major bump on this package as well.

Error handling changed (errors are thrown instead of returned) but that shouldn't be a big issue IMO.

**Comment by DanielRuf** [comment]
> The real issue with updating is probably not going to be the node version (as most of your users are probably on node >=10), but the fact that the minify() function is now async (I'm very sorry but I have to update to the new source-map). This will warrant a major bump on this package as well.
> 
> Error handling changed (errors are thrown instead of returned) but that shouldn't be a big issue IMO.

Ok, it seems we may have to change a few things then and ensure that they still work as expected. I'll plan some PR for September or October and a major release for the end of this year or next year when probably webpack 5 is released and I can discuss and coordinate this with the other package maintainers so they are aware of the planned roadmap and coming changes.

**Comment by evilebottnawi** [comment]
>  probably webpack 5 is released and I can discuss and coordinate this with the other package maintainers so they are aware of the planned roadmap and coming changes

You may not have noticed, but I am maintainer and I am asking you to do this asap, but you again ignore me

**Comment by evilebottnawi** [comment]
But no need, fork is WIP and `webpack` will be migrate on this

**Comment by DanielRuf** [comment]
> You may not have noticed, but I am maintainer and I am asking you to do this asap, but you again ignore me

I am aware of that but I see no good reasons to rush here (only for webpack) =)

Reopening as this is still relevant, not just for ebpack. Nothing critical that has to be done now.

**Comment by abdonrd** [comment]
There are any news here? Thanks in advance!

**Comment by DanielRuf** [comment]
No news here so far.

**Comment by fabiosantoscode** [comment]
> Ok, it seems we may have to change a few things then and ensure that the code still works as expected.

@DanielRuf fortunately await and Promise.resolve() turn non-promise things into promises.

PS I've migrated the terser org to travis-ci.com to fix an issue in PR builds over at the terser repo, hope you don't mind!

**Comment by laurentpayot** [comment]
I found out that my JS code inside my HTML was not minified at all because I was using the [now widespread](https://caniuse.com/mdn-javascript_operators_optional_chaining) optional chaining operator `?.`.
Optional chaining operator is supported by Terser since [version 5.2.0](https://github.com/terser/terser/blob/master/CHANGELOG.md#v520), but html-minifier-terser only uses version 4.6.3.

It's been a while since Terser 5 release, maybe it's time to update Terser to the latest version so people can use this package with modern JS syntax :wink:

**Comment by DanielRuf** [comment]
PRs are very welcome., I have currently no time.

**Comment by fabiosantoscode** [comment]
Please be patient fellow humans. Updating to Terser 5 is not a matter of bumping a version in package.json.

**Comment by slorber** [comment]
Hi.

As the Docusaurus 2 maintainer, we would also benefit from the terser v5 upgrade.
How complex is that upgrade? Can an external contributor easily work on this?

We have weird Yarn behavior (only affecting monorepos), where some users end up running this html-minifier-terser against Terser v5 instead of v4, which make the build fail. This seems to be the case when some other package of the monorepo depends on file-loader. (https://github.com/facebook/docusaurus/issues/3515)

```
(undefined) TypeError: Cannot read property 'replace' of undefined
    at Object.options.minifyJS (main:18614:28)
```

Was wondering if other projects are affected by this issue as well?

The workaround I found was to use nohoist:

```
"workspaces": {
    "packages": [
      "docs",
      "other-project"
    ],
    "nohoist": [
      "**/html-minifier-terser",
    ]
  }, 
```

We already have a few affected users by this problem.

This issue is likely not the fault of this package, but was just curious if others are sharing the same motivations for this terser v5 upgrade.

**Comment by DanielRuf** [comment]
> We have weird Yarn behavior (only affecting monorepos), where some users end up running this html-minifier-terser against Terser v5 instead of v4, which make the build fail

Even with yarn resolutions?

**Comment by slorber** [comment]
As far as I remember, I tried yarn resolutions and it didn't work. Wasn't able to get it fixed without nohoist.

**Comment by fabiosantoscode** [comment]
I suspect this has to be fixed at the yarn level.

Asking for a version of a package and not getting something outside that range is a very important, very critical task of any package manager.

I suspect that if you have source-map installed then you have two incompatible versions of it installed? The latest one is async (which is why Terser is async)

**Comment by slorber** [comment]
Yes I agree @fabiosantoscode , it's likely a Yarn issue (or maybe related to node resolution too).
I debugged the issue and can clearly see that this package calls Terser 5, and fail on `resultPromise.replace()` (terser 5) instead of the expected `result.replace()` (terser 4).

**Comment by alexander-akait** [comment]
> I'll wait until webpack 5 is released and webpack 4 deprecated.

@DanielRuf do we need wait something

webpack@5 was released a long time ago

**Comment by DanielRuf** [comment]
> > I'll wait until webpack 5 is released and webpack 4 deprecated.
> 
> @DanielRuf do we need wait something
> 
> webpack@5 was released a long time ago

Feel free to create the fork, I do not have much time at the moment and in the next weeks.

**Comment by alexander-akait** [comment]
@DanielRuf we need to change our API on async, do you agree? Don't wan to waste time

**Comment by DanielRuf** [comment]
I agree with this.
